### ISSUE TITLE
Doesn't work - Sprockets::FileNotFound

### ISSUE THREAD

**Issue by webmelzer** [bjevanchiu/bootstrap-table-rails#1]
couldn't find file 'bootstrap-table' with type 'application/javascript'

Added to gemfile:
gem 'bootstrap-table-rails', '~> 1.8.1'

bundle install successful
Using bootstrap-table-rails 1.8.1

Added to application.js
//= require bootstrap-table
//= require bootstrap-table-all
//= require bootstrap-table-locale-all

Running Rails 4.2.3

**Comment by erikgall** [comment]
@bjevanchiu @webmelzer Any fix for this, I'm having the same issue?

**Comment by bjevanchiu** [comment]
@webmelzer  @erikgall  There is a package issue, I released a new version '1.8.2' that fixed the issue.
