### ISSUE TITLE
No route matches [GET] "/assets/bootstrap-table.css.map

### ISSUE THREAD

**Issue by glafir** [bjevanchiu/bootstrap-table-rails#12]
I got this error on puma console.
`ActionController::RoutingError (No route matches [GET] "/assets/bootstrap-table.css.map"):
`
I finded this string in vendor/assets/javascripts/bootstrap-tableap-table/bootstrap-table.css in the end of it:
`/*# sourceMappingURL=bootstrap-table.css.map */
`

**Comment by glafir** [comment]
Remove this string, please!

**Comment by RockManJoe64** [comment]
Any action on this? I am also seeing the same 😢

**Comment by yusdirman** [comment]
I am having the same issue

**Comment by mlincoln1205** [comment]
I still have the same issue, any action?

**Comment by bjevanchiu** [comment]
fixed the issue aroud 1.16.0
