### ISSUE TITLE
Moving to using bootstrap-table 1.20 (to get bootstrap 5)?

### ISSUE THREAD

**Issue by theirishpenguin** [bjevanchiu/bootstrap-table-rails#15]
Hi Bejevanchiu,

Thanks for this project. Great work 👍 

I'm just wondering if you are planning to wrap  bootstrap-table 1.20, which introduces bootstrap 5?

From the bootstrap-table changelog...

![image](https://user-images.githubusercontent.com/39653/165973772-4da2b1a1-6c4f-4afe-9694-474b1ef72f34.png)

Or is there any technical reason that could block this?

**Comment by bjevanchiu** [comment]
Thx. Updated 1.20.2
