### ISSUE TITLE
JS SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by webmelzer** [bjevanchiu/bootstrap-table-rails#2]
The error is in bootstrap-table-all. I found this:

`table(a = a.replace(/[A-Za-z]/, ""), b.toLowerCase()) {case "s": a = +a; break;`

It looks like all of the `switch` statements are being replaced with `table`
I noticed it in 4 places total.

**Comment by bjevanchiu** [comment]
@webmelzer , this project doesn't handle the js source issues. 
You can submit your problem to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table).

**Comment by webmelzer** [comment]
Nope, the issue doesn't have to do with the JS source. I checked, and the JS is all valid in that project. Switch statements are there. The issue may have to do with whatever you are using to minify the original JS. My suggestion is that you leave the original JS source untouched and let the user deal with compressing it. There is really no reason to do it on your end, especially since "uglifier" comes standard in Rails.

**Comment by bjevanchiu** [comment]
@webmelzer  You are right. I have updated the the original JS source to latest version without any changes.  In fact I just picked the mini version instead of minifying the original JS source, for making the size of gem smaller.

**Comment by nmargaritis** [comment]
Could extensions/bootstrap-table-filter-control face exactly the same issue? It appears that I am getting the same error.

**Comment by nmargaritis** [comment]
@bjevanchiu it appears that I we were not using version 1.11.0. Upgrading to that solved the problem. Sorry for that.

**Comment by bjevanchiu** [comment]
@nmargaritis Glad to see your problem was solved.
