### ISSUE TITLE
Update to bootstrap-table 1.12.1?

### ISSUE THREAD

**Issue by cbolsen** [bjevanchiu/bootstrap-table-rails#9]
Thanks for putting together this very handy gem. I'm debugging some issues with bootstrap-table in my app, and suspect it could be fixed in the latest bootstrap-table version. Are there any plans to upgrade this in the near future?

**Comment by bjevanchiu** [comment]
@cbolsen Thank you! It has been upgraded to lastest version 1.12.1 .

**Comment by Insood** [comment]
Thanks for all your work!
